language: java
sudo: false
install: true

jobs:
  include:
    - stage: unit tests and integration tests
      script:
        - mvn clean integration-test
    - stage: package and deploy
      script:
        - echo -n $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - mvn clean deploy -DskipTests