language: java
sudo: false
install: true

jobs:
  include:
    - stage: tests and deploy
      script:
        - echo -n $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - mvn clean deploy