language: java
sudo: false

jobs:
  include:
    - stage: integration-test
      script:
        - mvn clean test-compile surefire:test
    -
      script:
        - mvn clean test-compile failsafe:integration-test
    - stage: package and deploy
      script:
        - echo -n $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - mvn clean deploy -DskipTests