version: "3"

services:
  app-db:
    image: postgres:10.2
    container_name: spring-app-db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
