spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true

spring-app:
  greeting:
    value: "Hello World"
  advanced-greeting:
    value: "Hello World from Spring"